/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesAddPropertyRouteImport } from './routes/properties/add-property'
import { Route as PropertiesIdRouteImport } from './routes/properties/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesAddPropertyRoute = PropertiesAddPropertyRouteImport.update({
  id: '/properties/add-property',
  path: '/properties/add-property',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/add-property': typeof PropertiesAddPropertyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/add-property': typeof PropertiesAddPropertyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/add-property': typeof PropertiesAddPropertyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/properties/$id' | '/properties/add-property'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/properties/$id' | '/properties/add-property'
  id: '__root__' | '/' | '/properties/$id' | '/properties/add-property'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  PropertiesAddPropertyRoute: typeof PropertiesAddPropertyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/add-property': {
      id: '/properties/add-property'
      path: '/properties/add-property'
      fullPath: '/properties/add-property'
      preLoaderRoute: typeof PropertiesAddPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  PropertiesAddPropertyRoute: PropertiesAddPropertyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
